version: '3' # specify docker-compose version

services:
  backend: #miam project: service backend
    build: ./backend # specify the directory of the Dockerfile
    ports:
      - "8083:8080" # maps port 4200 on localhost to 80 in container