version: "3"

services:
# FRONTEND CONTAINER
  frontend:
    build: ./frontend
    container_name: miam_frontend
    expose:
    - 80
    restart: unless-stopped # RESTART CONTAINER IF IT STOP
# BACKEND CONTAINER
  backend: #MIAM PROJECT: SERVICE 
    build: ./backend # THE DIRECTORY FILE OF DOCKERFILE
    network_mode: bridge
    container_name: miam_backend
    expose:
      - 8080
    ports:
      - 8083:8083 # MAPS PORT 8086 ON LOCALHOST TO 8080 IN CONTAINER
    restart: unless-stopped